core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', RedirectView.as_view(url='/supermarket/')),
    path('supermarket/', include('supermarket.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

supermarket/urls.py
from django.conf.urls import url

# Import views
from .views import (
    IndexView,
    CatagoryList,
    CatagoryDetail,
    ProductList,
    ProductDetail,
)

# App namespace
app_name = 'supermarket'

# URL Maps
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^catagories/$', CatagoryList.as_view(), name='catagory-list'),
    url(r'^catagory/(?P<pk>[0-9]+)/$', CatagoryDetail.as_view(), name='catagory-detail'),
    url(r'^products/$', ProductList.as_view(), name='product-list'),
    url(r'^product/(?P<pk>[0-9]+)/$', ProductDetail.as_view(), name='product-detail'),
]

supermarket/models.py
from django.db import models
from django.urls import reverse


class Catagory(models.Model):
    """
    Abstracts catagory of products
    Example: Electronics, Juice, Beverage, Snacks etc...
    """
    title = models.CharField('Catagory Title', max_length=60,)
    description = models.TextField(null=True, blank=True,)
    thumbnail = models.ImageField(
        upload_to='catagory/thumbnails/',
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ['title', ]
        verbose_name = 'Product Catagory'
        verbose_name_plural = 'Product Catagories'

    def sub_products(self):
        """
        Return a product list for the current catagory
        """
        return self.product_set.all()

    def get_absolute_url(self, *args, **kwargs):
        return reverse('supermarket:catagory-detail', args=[str(self.pk)])

    def __str__(self):
        return self.title


class Brand(models.Model):
    """
    Abstracts product brands
    Example: Mac-coffee, Nestle, Genesis Farm, Coca-cola, Sony etc...
    """
    title = models.CharField('Brand Title', max_length=60)
    description = models.TextField(null=True, blank=True)
    featured = models.BooleanField(default=False)

    class Meta:
        ordering = ['-featured', 'title', ]
        verbose_name = 'Product Brand'
        verbose_name_plural = 'Product Brands'

    def __str__(self):
        return self.title

    def get_absolute_url(self, *args, **kwargs):
        return reverse('supermarket:brand-detail', args=[str(self.pk)])


class Tag(models.Model):
    """
    Abstracts a Tag to identify a product
    Example:
    Sony, Electronics, LED, Entertainment
    """
    title = models.CharField('Tag Name', max_length=30)

    class Meta:
        ordering = ['title', ]

    def get_absolute_url(self, *args, **kwargs):
        return reverse('supermarket:tag-detail', args=[str(self.pk)])

    def __str__(self):
        return self.title


class Unit(models.Model):
    """
    Abstracts a Measurement Unit
    Example: no., meter, kg, liter etc...
    """
    title = models.CharField('Unit Name', max_length=60)
    html_title = models.CharField(
        max_length=30,
        help_text='Unit with superscript tags. Eg. m3, m2...',
    )

    class Meta:
        ordering = ['title', ]
        verbose_name = 'Measurement Unit'
        verbose_name_plural = 'Measurement Units'

    def __str__(self):
        return self.title


class Product(models.Model):
    """
    Abstracts a particular Product item
    Example: Mango Juice, 42' Sony LED TV, etc...
    """
    catagory = models.ForeignKey(Catagory, on_delete=models.CASCADE)
    brand = models.ForeignKey(
        Brand,
        null=True,
        blank=True,
        on_delete=models.SET_NULL
    )
    tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField('Product Name', max_length=100)
    description = models.TextField(
        'Product Description',
        null=True,
        blank=True
    )
    unit = models.ForeignKey(
        Unit,
        on_delete=models.CASCADE,
        verbose_name='Measurement Unit'
    )
    price = models.DecimalField(
        'Price Per Unit',
        max_digits=8,
        decimal_places=2
    )
    minimum_stock = models.FloatField(
        'Recommeded Minimum Stock Amount',
        null=True,
        blank=True
    )
    thumbnail = models.ImageField(
        upload_to='thumbnails/',
        null=True, blank=True
    )
    expiration_date = models.DateField(
        'Product Expiration Date',
        null=True,
        blank=True,
    )
    on_sale = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-on_sale', 'title', 'price', ]

    def get_absolute_url(self, *args, **kwargs):
        return reverse('supermarket:product-detail', args=[str(self.pk)])

    def __str__(self):
        return self.title


class Section(models.Model):
    """
    Abstract (section)location of a product in the Supermarket
    Example: Fruits Section, Snack Section, Beverage Section etc..
    """
    FLOOR_OPTIONS = (
        ('first', 'First Floor'),
        ('second', 'Second Floor'),
        ('third', 'Third Floor'),
    )
    title = models.CharField('Floor Section Title', max_length=60)
    floor = models.CharField(max_length=60, choices=FLOOR_OPTIONS)
    description = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['floor', 'title', ]

    def get_absolute_url(self, *args, **kwargs):
        return reverse('supermarket:section-detail', args=[str(self.pk)])

    def __str__(self):
        return self.title


class Inventory(models.Model):
    """
    Abstracts Product Inventory
    """
    section = models.ForeignKey(Section, null=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    stock = models.IntegerField(blank=True, null=True, default=0)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['product', ]

    def get_absolute_url(self, *args, **kwargs):
        return reverse('supermarket:Inventory-detail', args=[str(self.pk)])

    def __str__(self):
        return self.product.title

supermarket/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, TemplateView

# Import Mddels
from .models import (
    Catagory,
    Brand,
    Product,
)


class IndexView(TemplateView):
    """
    View for Index Page
    """
    template_name = 'supermarket/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super(IndexView, self).get_context_data(*args, **kwargs)
        context['catagory_list'] = Catagory.objects.all()
        return context


class CatagoryList(ListView):
    """
    View for listing all Product Catagory
    """
    model = Catagory

    def get_context_data(self, *args, **kwargs):
        context = super(CatagoryList, self).get_context_data(*args, **kwargs)
        context['product_list'] = Product.objects.all()
        context['brand_list'] = Brand.objects.filter(featured=True)
        return context


class CatagoryDetail(DetailView):
    """
    View for a particular Product Catagory Detail
    """
    model = Catagory

    def get_context_data(self, *args, **kwargs):
        context = super(CatagoryDetail, self).get_context_data(*args, **kwargs)
        context['catagory_list'] = Catagory.objects.all()
        context['brand_list'] = Brand.objects.filter(featured=True)
        context['total_product_count'] = Product.objects.all().count()
        context['product_list'] = Product.objects.filter(
            catagory=self.kwargs['pk']
        )
        return context


class ProductList(ListView):
    """
    View for listing all Products
    """
    model = Product


class ProductDetail(DetailView):
    """
    View for a particular Product Detail
    """
    model = Product

supermarket/templates/supermarket/catagory_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}
<title>Catagory List</title>
{% endblock title %}

{% block page_intro %}
<div class="search-row-wrapper">
    <div class="container ">
        <form action="category.html#" method="GET">
            <div class="row">


                <div class="col-md-3">
                    <input class="form-control keyword" type="text" placeholder="e.g. Mobile Sale">
                </div>
                <div class="col-md-3">
                    <select class="form-control selecter" name="category" id="search-category">
                        <option selected="selected" value="">All Categories</option>
                        <option value="Vehicles" style="background-color:#E9E9E9;font-weight:bold;"
                                disabled="disabled">- Vehicles -</option>
                        <option value="Cars">Cars</option>
                        <option value="Commercial vehicles">Commercial vehicles</option>
                        <option value="Motorcycles">Motorcycles</option>
                        <option value="Motorcycle Equipment">Car &amp; Motorcycle Equipment</option>
                        <option value="Boats">Boats</option>
                        <option value="Vehicles">Other Vehicles</option>
                        <option value="dropoff" style="background-color:#E9E9E9;font-weight:bold;"
                                disabled="disabled">- Extra -</option>
                        <option value="Other">Other</option>
                    </select>
                </div>
                <div class="col-md-3">
                    <select class="form-control selecter" name="location" id="id-location">
                        <option selected="selected" value="">All Brands</option>
                        <option value="AL">Nestle</option>
                        <option value="AK">Sony</option>
                    </select>
                </div>
                <div class="col-md-3">
                    <button class="btn btn-block btn-primary  "><i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock page_intro %}

{% block page_main %}
<div class="main-container">
    <div class="container">
        <div class="row">
            <!-- this (.mobile-filter-sidebar) part will be position fixed in mobile version -->
            <div class="col-md-3 page-sidebar mobile-filter-sidebar">
                <aside>
                    <div class="inner-box">
                        <div class="categories-list list-filter">
                            <h5 class="list-title"><strong><a href="category.html#">Categories</a></strong></h5>
                            <ul class=" list-unstyled">
                                <li {% if not catagory %} class="active" {% endif %}>
                                    <a href="{% url 'supermarket:catagory-list' %}">
                                      <span class="title">All</span>
                                      <span class="count">&nbsp; {{ total_product_count }}</span>
                                    </a>
                                </li>
                                {% for catagory in catagory_list %}
                                <li {% if catagory.id == object.id %}class="active"{% endif %}>
                                    <a href="{% url 'supermarket:catagory-detail' catagory.id %}">
                                      <span class="title">{{ catagory.title }}</span>
                                      {% if catagory.sub_products.count > 0 %}
                                      <span class="count">&nbsp;{{ catagory.sub_products.count }}</span>
                                      {% endif %}
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <!--/.categories-list-->

                        <div class="locations-list  list-filter">
                            <h5 class="list-title"><strong><a href="category.html#">Brands</a></strong></h5>
                            <ul class="browse-list list-unstyled long-list">
                                {% for brand in brand_list %}
                                <li><a href="#"> {{ brand.title }} </a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <!--/.brand-list-->

                        <div style="clear:both"></div>
                    </div>
                    <!--/.categories-list-->
                </aside>
            </div>
            <!--/.page-side-bar-->


            <div class="col-md-9 page-content col-thin-left">
                <div class="category-list">
                    <div class="listing-filter">
                        <div class="pull-left col-xs-6">
                            <div class="breadcrumb-list">
                                <a href="category.html#" class="current">
                                    <span>All ads</span>
                                </a>in
                                <span class="cityName"> New York </span> <a href="category.html#selectRegion" id="dropdownMenu1"
                                                                            data-toggle="modal"><span
                                        class="caret"></span></a>
                            </div>
                        </div>
                        <div style="clear:both"></div>
                    </div>

                    <div class="adds-wrapper">
                        {% for product in product_list %}
                        <div class="item-list make-grid" data-mh="product-list">

                            {% if product.on_sale %}
                            <div class="cornerRibbons topAds">
                               <span>On Sale</span>
                            </div>
                            {% endif %}

                            <div class="row">
                              <div class="col-md-2 no-padding photobox">
                                <div class="add-image">
                                    <a href="{% url 'supermarket:product-detail' product.id %}">

                                        {% if product.thumbnail %}
                                        <img class="thumbnail no-margin" src="{{ product.thumbnail.url }}" alt="img">
                                        {% else %}
                                        <img class="thumbnail no-margin" src="{% static 'images/default_thumbnails/product_thumbnail.png' %}" alt="img">
                                        {% endif %}
                                    </a>
                                </div>
                              </div>

                              <!--/.photobox-->
                              <div class="col-sm-7 add-desc-box">
                                <div class="ads-details">
                                    <h5 class="add-title text-center">
                                        <a href="{% url 'supermarket:product-detail' product.id %}">
                                        {{ product.title }}
                                        </a>
                                    </h5>

                                    <span class="info-row">
                                        <!-- <p>Price: {{ product.price }}</p> -->
                                    </span>
                                </div>
                              </div>
                              <!--/.add-desc-box-->
                              <div class="col-md-3 text-right  price-box">
                                <h5 class="item-price text-center"> ETB {{ product.price|intcomma }} </h5>
                              </div>
                            </div>
                        </div>
                        <!--/.item-list-->
                        {% endfor %}
                        <!--/.item-list-->
                    </div><!-- /.adds-wrapper -->
                   </div><!-- /.catagory-list -->

                <div class="pagination-bar text-center">
                    <nav aria-label="Page navigation " class="d-inline-b">
                        <ul class="pagination">

                            <li class="page-item active"><a class="page-link" href="category.html#">1</a></li>
                            <li class="page-item"><a class="page-link" href="category.html#">2</a></li>
                            <li class="page-item"><a class="page-link" href="category.html#">3</a></li>
                            <li class="page-item"><a class="page-link" href="category.html#">4</a></li>
                            <li class="page-item"><a class="page-link" href="category.html#">...</a></li>
                            <li class="page-item">
                                <a class="page-link" href="category.html#">Next</a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <!--/.pagination-bar -->
            </div>
            <!--/.page-content-->

        </div>
    </div>
</div>
{% endblock page_main %}

{% block vendor_js %}
<script type="text/javascript" src="{% static 'assets/plugins/match-height/jquery.matchHeight-min.js' %}"></script>
{% endblock vendor_js %}

supermarket/templates/supermarket/catagory_list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}
<title>Catagory List</title>
{% endblock title %}

{% block page_intro %}
<div class="search-row-wrapper">
    <div class="container ">
        <form action="category.html#" method="GET">
            <div class="row">


                <div class="col-md-3">
                    <input class="form-control keyword" type="text" placeholder="e.g. Mobile Sale">
                </div>
                <div class="col-md-3">
                    <select class="form-control selecter" name="category" id="search-category">
                        <option selected="selected" value="">All Categories</option>
                        <option value="Vehicles" style="background-color:#E9E9E9;font-weight:bold;"
                                disabled="disabled">- Vehicles -</option>
                        <option value="Cars">Cars</option>
                        <option value="Commercial vehicles">Commercial vehicles</option>
                        <option value="Motorcycles">Motorcycles</option>
                        <option value="Motorcycle Equipment">Car &amp; Motorcycle Equipment</option>
                        <option value="Boats">Boats</option>
                        <option value="Vehicles">Other Vehicles</option>
                        <option value="dropoff" style="background-color:#E9E9E9;font-weight:bold;"
                                disabled="disabled">- Extra -</option>
                        <option value="Other">Other</option>
                    </select>
                </div>
                <div class="col-md-3">
                    <select class="form-control selecter" name="location" id="id-location">
                        <option selected="selected" value="">All Brands</option>
                        <option value="AL">Nestle</option>
                        <option value="AK">Sony</option>
                    </select>
                </div>
                <div class="col-md-3">
                    <button class="btn btn-block btn-primary  "><i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock page_intro %}

{% block page_main %}
<div class="main-container">
    <div class="container">
        <div class="row">
            <!-- this (.mobile-filter-sidebar) part will be position fixed in mobile version -->
            <div class="col-md-3 page-sidebar mobile-filter-sidebar">
                <aside>
                    <div class="inner-box">
                        <div class="categories-list list-filter">
                            <h5 class="list-title"><strong><a href="category.html#">Categories</a></strong></h5>
                            <ul class=" list-unstyled">
                                <li {% if not catagory %} class="active" {% endif %}>
                                    <a href="{% url 'supermarket:catagory-list' %}">
                                      <span class="title">All</span>
                                      <span class="count">&nbsp; {{ product_list.count }}</span>
                                    </a>
                                </li>
                                {% for catagory in catagory_list %}
                                <li {% if catagory.id == object.id %}class="active"{% endif %}>
                                    <a href="{% url 'supermarket:catagory-detail' catagory.id %}">
                                      <span class="title">{{ catagory.title }}</span>
                                      {% if catagory.sub_products.count > 0 %}
                                      <span class="count">&nbsp;{{ catagory.sub_products.count }}</span>
                                      {% endif %}
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <!--/.categories-list-->

                        <div class="locations-list  list-filter">
                            <h5 class="list-title"><strong><a href="category.html#">Brands</a></strong></h5>
                            <ul class="browse-list list-unstyled long-list">
                                {% for brand in brand_list %}
                                <li><a href="#"> {{ brand.title }} </a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <!--/.locations-list-->

                        <div style="clear:both"></div>
                    </div>
                    <!--/.categories-list-->
                </aside>
            </div>
            <!--/.page-side-bar-->


            <div class="col-md-9 page-content col-thin-left">
                <div class="category-list">
                    <div class="listing-filter">
                        <div class="pull-left col-xs-6">
                            <div class="breadcrumb-list">
                                <a href="category.html#" class="current">
                                    <span>All ads</span>
                                </a>in
                                <span class="cityName"> New York </span> <a href="category.html#selectRegion" id="dropdownMenu1"
                                                                            data-toggle="modal"><span
                                        class="caret"></span></a>
                            </div>
                        </div>
                        <div style="clear:both"></div>
                    </div>

                    <div class="adds-wrapper">
                        {% for product in product_list %}
                        <div class="item-list make-grid" data-mh="product-list">

                            {% if product.on_sale %}
                            <div class="cornerRibbons topAds">
                                <a href="#">On Sale</a>
                            </div>
                            {% endif %}

                            <div class="row">
                              <div class="col-md-2 no-padding photobox">
                                <div class="add-image">
                                    <a href="{% url 'supermarket:product-detail' product.id %}">

                                        {% if product.thumbnail %}
                                        <img class="thumbnail no-margin" src="{{ product.thumbnail.url }}" alt="img">
                                        {% else %}
                                        <img class="thumbnail no-margin" src="{% static 'images/default_thumbnails/product_thumbnail.png' %}" alt="img">
                                        {% endif %}
                                    </a>
                                </div>
                              </div>

                              <!--/.photobox-->
                              <div class="col-sm-7 add-desc-box">
                                <div class="ads-details">
                                    <h5 class="add-title text-center">
                                        <a href="#">
                                        {{ product.title }}
                                        </a>
                                    </h5>

                                    <span class="info-row">
                                        <!-- <p>Price: {{ product.price }}</p> -->
                                    </span>
                                </div>
                              </div>
                              <!--/.add-desc-box-->
                              <div class="col-md-3 text-right  price-box">
                                <h5 class="item-price text-center"> ETB {{ product.price|intcomma }} </h5>
                              </div>
                            </div>
                        </div>
                        <!--/.item-list-->
                        {% endfor %}
                        <!--/.item-list-->
                    </div><!-- /.adds-wrapper -->
                   </div><!-- /.catagory-list -->

                <div class="pagination-bar text-center">
                    <nav aria-label="Page navigation " class="d-inline-b">
                        <ul class="pagination">

                            <li class="page-item active"><a class="page-link" href="category.html#">1</a></li>
                            <li class="page-item"><a class="page-link" href="category.html#">2</a></li>
                            <li class="page-item"><a class="page-link" href="category.html#">3</a></li>
                            <li class="page-item"><a class="page-link" href="category.html#">4</a></li>
                            <li class="page-item"><a class="page-link" href="category.html#">...</a></li>
                            <li class="page-item">
                                <a class="page-link" href="category.html#">Next</a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <!--/.pagination-bar -->
            </div>
            <!--/.page-content-->

        </div>
    </div>
</div>
{% endblock page_main %}

{% block vendor_js %}
<script type="text/javascript" src="{% static 'assets/plugins/match-height/jquery.matchHeight-min.js' %}"></script>
{% endblock vendor_js %}

supermarket/templates/supermarket/product_list.html
{% extends 'base.html' %}

{% block main %}
<h2>Product Lists</h2>
{% for product in product_list %}
<p>{{ product.title }}</p>
{% endfor %}
{% endblock main %}